
services:

  mysql:
    image: mysql:8
    container_name: bwr-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: bwr-backend
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ecommerce
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      JWT_SECRET: hknOOi2bMqcggcdSO8njLgbwgJE4/A6bL6m1mrLdQFI=
      CLOUDINARY_CLOUD_NAME: dgqjia7ca
      CLOUDINARY_API_KEY: 589256882176879
      CLOUDINARY_API_SECRET: TUW5q8zx-d3iwHACvWCfOPucxb0

  frontend:
    build: ./frontend
    container_name: bwr-frontend
    ports:
      - "3000:80"
    environment:
      VITE_RAZORPAY_KEY: rzp_test_SL9oidq4fiKDlT
    depends_on:
      - backend

volumes:
  mysql_data: